# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - phorge_web:/var/www/html
      - caddy_data:/data
      - ./phorge_caddyfile:/etc/caddy/Caddyfile
    networks:
      - phorge
    ports:
      # CHANGE TO "80:80" IF USING CADDY FOR HTTPS
      - "9080:80"
      # UNCOMMENT IF USING CADDY FOR HTTPS
      # - "443:443"
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=:80
      - HTTPS=off

  mariadb:
    image: mariadb:latest
    # https://hub.docker.com/_/mariadb
    volumes:
      - phorge_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
    command: --innodb-buffer-pool-size=268435456 --local-infile=0 --max-allowed-packet=33554432 --sql-mode=STRICT_ALL_TABLES
    networks:
      - phorge_db

  phorge:
    image: frank/phorge:latest
    # https://hub.docker.com/r/zeigren/phorge
    volumes:
      - phorge_web:/var/www/html
      - phorge_ssh:/etc/ssh
      - phorge_repo:/var/repo
      - phorge_lfs:/var/file_storage
      # - ./config/phorge_mailers.json:/usr/src/docker_ph/mailers.json
    environment:
      # set UPGRADE_ON_RESTART to true to update phorge
      - UPGRADE_ON_RESTART=false
      - PH_BASE_URI=https://phorge.yourdomain.test
      - PH_MYSQL_PASS=CHANGEME
      - PH_LOCAL_FILE_STORAGE=true
      # - PH_CLUSTER_MAILERS=true
    networks:
      - phorge
      - phorge_db
    ports:
      # SSH Port
      - 2530:2530

volumes:
  phorge_db:
    driver: local
    driver_opts:
      type: none
      device: /home/phorge/data
      o: bind
  phorge_web:
  phorge_ssh:
  phorge_repo:
    driver: local
    driver_opts:
      type: none
      device: /home/phorge/repos
      o: bind
  phorge_lfs:
    driver: local
    driver_opts:
      type: none
      device: /home/phorge/files
      o: bind
  caddy_data:

networks:
  phorge:
  phorge_db:
